name: coding_challenge
description: Coding Challenge

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.3
  font_awesome_flutter: ^9.0.0
  geolocator: ^7.0.1
  get_it: ^6.0.0
  google_fonts: ^1.1.2
  google_maps_flutter: ^2.0.1
  loading_indicator: ^1.2.0
  url_launcher: ^6.0.2
  
  
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  mockito:

flutter:
  uses-material-design: true
  assets:
    - assets/map/config.json
