name: coding_challenge
description: Coding Challenge

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.3
  google_maps_flutter: ^2.0.1
  
  
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  mockito:

flutter:
  uses-material-design: true
